spine_exporter_repo_param_name = "/registrations/prod/data-pipeline/ecr/url/spine-exporter"
log_group_param_name           = "/registrations/prod/data-pipeline/cloudwatch-log-group-name"
execution_role_arn_param_name  = "/registrations/prod/data-pipeline/ecs-execution-role-arn"
splunk_url_param_name          = "/registrations/prod/user-input/splunk-api-url"
splunk_api_token_param_name    = "/registrations/prod/user-input/splunk-api-token"