sonar.projectKey=prm-mi_prm-data-pipelines
sonar.organization=prm-mi

# This is the name and version displayed in the SonarCloud UI.
# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=prm-data-pipelines
#sonar.projectVersion=1.0
sonar.language=py
sonar.python.version=3.11
sonar.sources=lambda

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.
sonar.sources=lambda/, stacks/

sonar.sourceEncoding=UTF-8