s3_dashboard_bucket_name        = "prm-service-dashboard-prod"
alternate_domain_name           = "gp-registrations-data.nhs.uk"
gp2gp_dashboard_repo_param_name = "/registrations/prod/data-pipeline/ecr/url/gp2gp-dashboard"
log_group_param_name            = "/registrations/prod/data-pipeline/cloudwatch-log-group-name"
execution_role_arn_param_name   = "/registrations/prod/data-pipeline/ecs-execution-role-arn"
metrics_input_bucket_param_name = "/registrations/prod/data-pipeline/metrics-calculator/output-bucket-name"