name: SonarCloud-Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]


permissions:
  pull-requests: write
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  
jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r lambda/requirements.txt || true

      - name: Run SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v4
        with:
          projectBaseDir: lambda
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}